esi-test-app/esi_test_app/urls.py
from django.urls import path

from . import views

app_name = 'esi_test_app'
urlpatterns = [
    path('', views.index, name='index'),
    path(
        'test_token_required_1',
        views.test_token_required_2,
        name='test_token_required_1'
    ),
    path(
        'test_token_required_2',
        views.test_token_required_2,
        name='test_token_required_2'
    ),
    path(
        'test_single_use_token',
        views.test_single_use_token,
        name='test_single_use_token'
    ),
    path('run_api_test', views.run_api_test, name='run_api_test'),
]

esi-test-app/esi_test_app/views.py
import logging

from django.shortcuts import render, redirect

from esi.clients import EsiClientProvider
from esi.models import Token
from esi.decorators import token_required, single_use_token

from esi import __version__

# create client provider
esi = EsiClientProvider(app_info_text=f"esi-test-app {__version__}")

# setup logger
logger = logging.getLogger(__name__)
f_handler = logging.FileHandler('esi_test_api.log')
f_format = logging.Formatter(
    '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
f_handler.setFormatter(f_format)
logger.addHandler(f_handler)
logger.setLevel(logging.DEBUG)


ESI_SCOPES = ['esi-characters.read_medals.v1']


def index(request):
    """Start page with ability to login"""
    return render(
        request,
        'esi_test_app/index.html', context={'scopes': ESI_SCOPES}
    )


@single_use_token(scopes=ESI_SCOPES)
def test_single_use_token(request, token):
    request.session['token_pk'] = token.pk
    request.session['test_name'] = 'test 1 - single_use_token'
    return redirect('esi_test_app:run_api_test')


def test_token_required_1(request):
    """Preparing environment for test"""
    logger.info('--------------------------------------------')
    logger.info('starting API test with user {}'.format(request.user.username))
    Token.objects.filter(user=request.user, scopes__name__in=ESI_SCOPES).delete()
    return redirect('esi_test_app:test_token_required_2')


@token_required(scopes=ESI_SCOPES)
def test_token_required_2(request, token):
    request.session['token_pk'] = token.pk
    request.session['test_name'] = 'test 2 - token_required'
    return redirect('esi_test_app:run_api_test')


def run_api_test(request):
    """Running the API test"""
    logger.info('starting ESI client')
    token = Token.objects.get(pk=request.session['token_pk'])

    try:
        logger.info('making call to ESI with token')
        esi.client.Character\
            .get_characters_character_id_medals(
                character_id=token.character_id,
                token=token.valid_access_token()
            )\
            .result()
        test_success = True
        error_str = None
        logger.info('API test succeeded')

    except Exception as ex:
        test_success = False
        logger.exception('API test failed: {}'.format(ex))
        error_str = str(ex)

    context = {
        'test_name': request.session['test_name'],
        'test_success': test_success,
        'error_str': error_str,
        'esi_endpoint': '/characters/{character_id}/medals/'
    }
    return render(request, 'esi_test_app/test_result.html', context)

esi-test-app/esi_test_app/templates/esi_test_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ESI Test App</title>

    {% block extra_css %}{% endblock extra_css %}
</head>
<body>
{% block details %}{% endblock %}
</body>
</html>

esi-test-app/esi_test_app/templates/esi_test_app/index.html
{% extends 'esi_test_app/base.html' %}

{% block details %}

    <h1>Manual API test - Start</h1>

    <p>
        Welcome to esi-test-app!
    </p>
    <p>
        The purpose of this app is to allow testing of features of the django-esi app that require user interaction and can therefore not be tested with automated unit tests.<br>
        This test will try to first acquire an ESI token for the current user and then call an ESI endpoint with that token.
    </p>

    <p>
            <a href="{% url 'esi_test_app:test_single_use_token' %}">
                Run test 1 - single_use_token
            </a>
    </p>

    {% if request.user.is_authenticated == False %}

        <p>
            For running test 2 you need to be logged in with a staff account. Click
            <a href="{% url 'admin:login' %}?next={% url 'esi_test_app:index' %}">here</a>
             to login.
            </p>

    {% else%}
        <p>
            You are logged in as user: <b>{{ request.user.username }}</b>
            <a href="{% url 'admin:logout' %}?next={% url 'esi_test_app:index' %}">[Logout]
            </a>
        </p>

        <p>
            <strong>Important!</strong>
            For this test to work this app needs to delete <u>any</u> ESI tokens of user <b>{{ request.user.username }}</b> which has the scopes mentioned below.
            Please make sure there are no other apps running in this Django site that are using ESI tokens:
        </p>
        <ul>
            {% for scope in scopes %}
                <li><code> {{ scope }} </li></code>
            {% endfor%}
        </ul>

        <p>
            <a href="{% url 'esi_test_app:test_token_required_1' %}">
                Run test 2 - token_required
            </a>
        </p>

    {% endif %}

{% endblock %}

{% block extra_css %}
{% endblock extra_css %}

esi-test-app/esi_test_app/templates/esi_test_app/test_result.html
{% extends 'esi_test_app/base.html' %}

{% block details %}

    <h1>API test result: {{ test_name }}</h1>

    <p>Used ESI endpoint: <code>{{ esi_endpoint }}</code></p>

    {% if test_success %}
        <p style="color: green"><strong>Test suceeded !!</strong></p>

    {% else%}
        <p style="color: red"><strong>Test failed.</strong> </p>
        <p>Error:<br>
        <code>{{ error_str }}</code></p>
        </p>Please check log file for details</p>

    {% endif %}

    <p><a href="{% url 'esi_test_app:index' %}">Back to start page</a></p>

{% endblock %}

{% block extra_css %}
{% endblock extra_css %}